/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 15.01.2026 15:58:08

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 8
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 10128;
#else
constexpr int kTensorArenaSize = 9104;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,3960 } };
const TfArray<1, float> quant0_scale = { 1, { 0.003553921589627862, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 99, 40, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 99, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 50, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 50, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data5[2] = { -1, 400, };
const TfArray<1, int> tensor_dimension5 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data6[3] = { -1293, 1057, -512, };
const TfArray<1, int> tensor_dimension6 = { 1, { 3 } };
const TfArray<1, float> quant6_scale = { 1, { 0.00012609046825673431, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[3*400] = { 
  -41, -63, -64, -112, 21, 16, -20, -89, -76, -28, -3, -44, -23, -12, 6, -35, -15, -51, 3, -26, -17, 18, 22, 23, -24, -35, 17, -16, -21, -4, 21, -69, -16, -14, -16, -2, 9, -22, -20, 20, -20, -26, 37, 17, 37, -6, 11, -65, -7, -12, -24, -29, -39, -30, 3, 3, 7, -19, 41, -20, 2, -16, -7, -64, -2, 1, -26, 13, 34, 19, -5, -54, -27, -3, -23, 23, 1, -7, -14, -47, -3, -45, 20, 12, 32, 1, 13, 25, -14, 30, 36, 1, 15, 50, 33, -74, -3, 2, 18, 29, -35, 35, 14, -11, 31, -18, 14, 13, 23, -3, -17, -32, 2, 18, 3, -25, 24, 14, -19, 8, 15, -13, 6, -18, -16, 31, 16, -73, 11, -2, -16, 23, 64, 9, 12, -3, 23, -13, 31, 23, 25, 19, 15, -64, 11, 32, 16, 34, 91, 8, 54, 21, 6, 0, 32, 25, 55, 9, 33, -23, 46, 1, 14, 36, 36, 40, 39, 19, 18, 23, 25, 38, 46, 38, 45, -31, 4, 4, 26, 24, 16, 1, 16, 7, 22, 39, 12, 18, 13, 14, 30, -55, 19, 26, 1, 3, 19, 35, 8, 26, 6, 25, 17, 14, 22, 8, 13, -29, -13, -18, 6, 23, -31, -16, -1, 3, 22, 14, -9, 18, 18, -10, 12, -48, -23, -20, -4, -10, 83, 1, -11, -28, 22, 2, 14, 20, 17, 42, -14, -57, 29, 17, -4, 8, 41, -12, 10, 47, 7, -5, 6, 27, 52, 26, 2, -24, -6, -22, 23, 4, -22, -26, 16, 27, -21, 8, 34, 26, 10, -12, 33, -60, -21, -18, -26, -27, 29, 11, 9, -43, -19, -31, 3, -5, 31, -31, -28, -20, -18, -1, 22, -26, -20, -23, 4, 25, -4, -20, 5, 1, 18, 44, 21, -32, -7, -26, -4, 22, -45, 22, 20, 17, 17, 38, 25, -3, 29, 16, 14, -51, 30, -8, 40, 18, -63, 11, 8, 20, 11, 8, 33, 7, 34, -42, 17, -25, -38, 6, -47, 30, -70, -19, 8, -18, 15, -16, -16, 4, 10, -52, -21, -57, -69, -57, -66, -71, -6, -46, -49, -51, -26, -58, -20, -25, -51, -65, -64, -33, -67, -36, -38, -35, -50, -30, -53, -33, -42, -34, -78, -21, -83, -60, -63, -56, -79, -48, -60, -58, -53, -59, -69, -74, -54, -48, -41, -61, -56, -76, -77, -37, 
  19, 37, 9, 8, -71, -1, 0, -20, 35, 3, 0, 17, -4, -4, -12, 60, 16, 42, 3, 49, -41, -17, 8, -9, 8, 26, 19, 13, -14, -35, 19, 39, 41, 26, -23, -11, -13, -40, -4, -6, 21, -1, -33, -13, -38, -55, -10, 47, 12, -2, -9, 10, 43, 6, -22, -2, -4, 0, -16, -8, 16, 63, 11, 45, 46, 36, 34, 36, -47, -18, 37, 32, 23, 35, 5, 28, 5, -21, -12, 33, -15, 25, -8, 2, 14, 16, 1, -16, 33, 11, -2, 16, -19, 13, -38, 53, -12, 3, 19, 34, -98, -41, -20, -8, -1, -9, -46, -7, -33, -17, -4, 74, -29, -12, 11, 31, -20, -12, 14, -29, -6, 8, -34, -38, -6, -41, -24, 18, -26, -1, -15, 1, -32, -19, -19, -59, -33, -27, -18, -18, -7, -19, -5, 45, -13, 13, 19, 8, -23, 3, -9, 5, 4, -9, -23, -16, -41, 7, 11, 49, 13, 17, -8, 15, -43, -21, 23, -41, -4, 5, -52, 10, 8, -40, -8, 36, -7, -21, 8, 9, -127, -22, -4, -20, -2, 5, -22, -40, -44, -55, -37, 56, -27, -32, -42, -15, -24, -66, -23, -38, -23, -22, -3, -4, -47, -55, -30, 24, 6, -43, -25, -28, -21, -30, -52, -12, -10, 3, -28, -17, -32, 9, -3, 55, -10, 20, 14, 29, -49, -20, 20, 23, 31, 4, -30, -4, 2, -16, 17, 41, -14, 20, 24, 41, -48, -36, 25, 6, -10, -9, 7, 5, -4, -56, -20, 12, 8, -8, -33, -2, -29, -26, -28, -4, 2, 6, -17, -6, -14, -47, -17, 38, -14, 22, 12, 5, -54, -28, -24, -16, 8, 9, -9, -12, -26, -43, -25, 3, -9, -8, -4, -25, -54, -27, -32, -17, -10, -31, 4, -22, -32, -38, -26, 58, -8, 12, -18, -27, 51, -33, -13, -29, -1, 7, -22, -1, -52, -7, -27, 62, 20, 43, 5, 50, -23, 10, 19, 50, 19, 28, 7, -16, -11, -5, 55, 61, 48, 39, 51, 28, -40, 12, 41, 30, 35, 39, 28, 46, 11, -10, 19, 42, 15, 43, 52, 53, -31, 24, 26, 20, 5, 37, -10, 1, 44, 21, 31, 55, 20, 36, 31, 38, -58, -5, -11, -2, 52, 30, 5, 20, 6, 7, 35, 61, 3, 16, 9, 24, -32, -17, 14, -10, 14, 20, -21, -1, 29, -33, 35, 48, 
  18, 12, 63, 40, -21, -14, 24, 29, 36, 36, 34, 13, 22, 27, 18, -5, 11, 0, -10, 10, 55, 41, 11, -45, -20, 16, 9, 33, 23, 6, -9, -13, -25, -5, 20, 2, 29, 22, -7, 27, -12, -27, -19, 11, 16, 36, -3, -21, -2, -7, 1, -17, -14, -11, -12, -11, 1, 3, -11, 7, -5, -73, -54, -8, -6, 2, -21, -34, 12, -5, -27, 3, -52, -38, -30, -12, -3, 55, -15, -36, -25, -12, 21, -49, -31, -41, -31, 8, -20, 6, -82, -18, 2, -10, -5, -2, -27, -27, -7, -6, 41, 29, -21, 18, 5, -18, -24, -15, -18, 14, 12, 6, -8, -15, 26, -37, 0, 34, 27, 29, 16, -16, 24, -14, -18, -6, -7, -17, 17, 10, 0, -12, -32, -29, 19, 26, -4, 1, -35, 7, 21, -19, 1, -19, -28, -38, -14, -13, -66, -9, 3, -97, -34, 18, -3, -26, -35, -58, -57, -43, -20, -12, -30, -21, 6, -5, -41, 2, -21, -39, -9, -21, -34, -31, -30, -4, 16, -26, 6, 0, 32, 7, 20, 23, -30, -30, 10, 13, 8, 25, 24, 16, 41, 5, 29, 11, 47, 25, 32, 48, 17, 15, 18, 2, 25, 11, 14, -7, -1, 0, 10, 2, 43, 37, 11, -14, 15, -1, 13, 13, 32, 13, -2, -11, -13, 15, 8, -4, -82, 11, 0, -31, 19, -11, 39, 26, -14, -35, -27, -8, -20, 15, -52, -28, 31, 29, -26, -41, 8, 5, 11, 26, -8, 20, -19, -9, -6, 12, 5, 8, 36, 20, -9, 11, -3, 25, -47, 15, -11, -3, -11, 0, 10, 1, 13, -4, -10, -11, 9, -13, -17, 14, 2, -12, -8, 42, 11, 19, -2, 17, -9, 0, 8, -10, 0, 22, 12, -11, 9, -27, -10, 18, -15, 11, 14, -2, -6, -8, -49, 20, -3, 18, 2, -29, -42, -18, -14, -14, 1, -1, -23, -12, -48, -48, 56, -22, -36, -42, -13, -10, -63, -45, -10, 3, -59, -15, -19, -54, -19, -52, 61, -19, -43, 27, -63, -62, -15, -33, -20, 16, 11, 5, 18, -4, 12, -29, 69, 33, 17, 4, -27, -26, 10, -8, 10, 22, -9, -20, 22, 0, 39, -10, 64, 44, 26, 38, 0, 16, 11, 24, 3, 64, 10, -7, 9, 40, 13, 14, 28, 9, 8, 17, 5, 28, 38, 9, 41, 44, 45, -17, 
};
const TfArray<2, int> tensor_dimension7 = { 2, { 3,400 } };
const TfArray<1, float> quant7_scale = { 1, { 0.0045507028698921204, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[16] = { 997, 967, -95, 553, -412, -711, -848, -515, 18, 858, -672, 327, -508, -428, -497, 1830, };
const TfArray<1, int> tensor_dimension8 = { 1, { 16 } };
const TfArray<16, float> quant8_scale = { 16, { 0.00010097531048813835, 0.00011091241321992129, 8.3014412666670978e-05, 0.00010644739813869819, 0.00012865652388427407, 9.5169627456925809e-05, 9.899853466777131e-05, 9.6452007710468024e-05, 0.0001190075563499704, 8.5879393736831844e-05, 7.118577923392877e-05, 0.00011588045890675858, 9.7791773441713303e-05, 0.00012624832743313164, 0.00012014776439173147, 0.00010230696352664381, } };
const TfArray<16, int> quant8_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[16*1*3*8] = { 
  /* [0][0][][] */ 90,64,127,50,16,6,-17,55, 74,-39,12,-6,11,31,30,-57, 55,32,23,-1,-31,-26,34,0, 
  /* [1][0][][] */ -12,51,35,36,51,-45,-14,68, -9,-58,8,-7,112,89,4,127, 99,-6,47,-64,24,-31,-5,32, 
  /* [2][0][][] */ 8,99,-10,0,-45,-39,6,56, 127,-4,68,80,85,-84,-67,106, -76,-13,14,-54,24,4,77,10, 
  /* [3][0][][] */ 100,-90,29,-26,127,-18,-70,52, 65,-83,12,75,69,-24,-70,46, 2,-20,-6,-16,102,-1,31,61, 
  /* [4][0][][] */ -95,-97,-73,-92,-127,-57,-39,-12, -100,-9,-27,-49,-86,35,-7,-36, 90,114,117,22,-65,53,-11,11, 
  /* [5][0][][] */ -66,72,25,66,-38,-89,-51,63, -109,77,-33,-54,49,58,-104,-42, -43,127,86,25,-34,-1,-84,26, 
  /* [6][0][][] */ 127,8,21,67,-85,-15,13,23, 72,-55,36,-62,-9,0,-43,53, -18,-103,-78,64,-48,8,-84,-57, 
  /* [7][0][][] */ -34,118,9,-127,-113,74,56,-32, 96,118,88,123,58,59,35,23, 4,-72,-92,-10,76,19,46,-18, 
  /* [8][0][][] */ 94,-75,39,49,102,-7,36,64, -26,-66,-83,33,127,-7,-114,92, 10,-42,41,5,46,52,-52,2, 
  /* [9][0][][] */ 88,-8,62,60,42,87,50,62, 43,-66,-1,-65,127,69,-74,72, 32,-103,-67,58,32,65,-31,97, 
  /* [10][0][][] */ -34,-127,-101,83,23,-75,44,-92, -94,-36,-19,18,-23,-117,-124,-47, 6,-15,-77,118,-42,34,-59,50, 
  /* [11][0][][] */ -45,11,-62,65,88,22,-39,-46, -31,-61,0,-7,127,-57,-24,14, -2,-10,-62,45,-71,-49,-70,-25, 
  /* [12][0][][] */ -53,127,-48,116,-48,-11,66,-62, 92,26,-73,2,-86,51,-78,-75, 49,86,38,45,48,-77,-27,-21, 
  /* [13][0][][] */ -50,-21,-43,-80,-127,44,-67,-61, 47,92,2,10,-107,-50,-45,-51, -12,79,84,19,65,-43,-51,27, 
  /* [14][0][][] */ 31,-18,-1,-14,-7,47,-8,-75, 40,127,64,17,26,7,33,-64, 106,-99,-28,84,62,-52,32,-66, 
  /* [15][0][][] */ 57,-31,13,-25,44,-20,-42,127, 31,-42,108,-23,28,-38,-14,113, 7,-59,115,-33,-62,6,-32,119, 
};
const TfArray<4, int> tensor_dimension9 = { 4, { 16,1,3,8 } };
const TfArray<16, float> quant9_scale = { 16, { 0.0034351868089288473, 0.0037732478231191635, 0.0028241558466106653, 0.0036213474813848734, 0.0043769036419689655, 0.003237677039578557, 0.0033679367043077946, 0.0032813036814332008, 0.0040486450307071209, 0.0029216227121651173, 0.002421744866296649, 0.0039422609843313694, 0.0033268826082348824, 0.0042949765920639038, 0.0040874350816011429, 0.003480489831417799, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[8] = { -365, -10270, 6106, -4980, -2137, -8693, -3605, 8661, };
const TfArray<1, int> tensor_dimension10 = { 1, { 8 } };
const TfArray<8, float> quant10_scale = { 8, { 1.4264160199672915e-05, 1.756404890329577e-05, 1.3683460565516725e-05, 1.1378184353816323e-05, 1.2172762581030838e-05, 7.438621196342865e-06, 7.2550778895674739e-06, 1.1769289812946226e-05, } };
const TfArray<8, int> quant10_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[8*1*3*40] = { 
  /* [0][0][][] */ 28,62,67,77,5,15,28,-48,-68,-40,26,-54,25,-64,-83,-3,-22,-37,-23,-60,16,-9,4,22,10,-26,-17,-60,-7,-60,-54,30,19,-13,34,-4,19,5,55,68, 56,65,34,113,51,31,76,45,-12,0,75,68,-44,39,12,37,49,4,-7,41,-32,47,27,7,-14,-38,26,-12,34,-20,-22,61,-7,-5,19,43,59,61,16,57, 56,39,127,43,112,-2,-11,-13,-35,27,-3,-40,11,-58,-54,-25,-53,-43,26,-37,36,-20,-8,13,3,-59,-67,-5,-33,-32,-47,-38,1,-14,-1,-7,-6,70,68,68, 
  /* [1][0][][] */ -97,-102,-93,-49,-127,-47,-113,-29,-73,-67,-91,-108,-29,-81,-9,-31,-87,-68,-19,-25,-48,-87,-42,-60,-56,-81,-96,-80,-91,-59,-60,-108,-83,-53,-53,-37,-92,-100,-73,-98, 58,10,-24,9,-7,46,51,60,31,11,5,11,54,1,5,60,27,0,-2,-4,36,57,-4,-3,-31,11,15,-16,1,39,0,10,5,46,15,2,-16,-6,-10,-44, 67,11,32,7,-20,64,77,53,20,64,4,63,82,23,49,59,35,75,77,26,24,53,-2,41,45,72,3,63,11,-13,42,-1,30,-22,1,48,43,16,-20,30, 
  /* [2][0][][] */ 51,92,20,61,30,-2,49,40,-34,6,64,-37,-16,-101,-91,-8,-2,-76,17,9,57,2,-2,13,13,-71,-81,-76,-11,-59,-40,4,-72,-10,-1,-85,-20,-65,-22,-40, 46,45,99,79,102,71,75,-10,57,-34,94,-28,-46,-2,21,6,-59,-33,42,52,39,84,0,29,-15,49,-35,-2,-26,-30,-5,57,-49,-2,-39,-50,-67,27,-32,-18, 72,18,60,89,127,50,104,81,39,-23,-5,-2,0,6,-7,14,-47,-48,57,-36,58,44,-15,44,61,-45,8,-20,19,53,39,-5,4,-47,25,-33,2,59,-14,-25, 
  /* [3][0][][] */ 14,44,-14,-87,17,-47,43,16,59,-19,19,-23,38,63,71,61,120,80,70,42,69,79,77,69,36,58,66,-45,43,11,26,42,62,58,59,67,10,32,-32,75, 3,5,-28,-64,-14,-3,37,-34,81,68,-39,13,20,11,114,28,127,97,43,59,71,66,43,87,25,-38,59,-25,8,-24,60,73,49,34,17,29,49,2,98,5, 71,10,31,-97,-15,18,2,27,-50,32,63,-40,-4,63,-16,73,72,41,6,81,-7,62,-18,26,-14,8,71,27,43,-57,59,-36,23,30,-1,38,56,-26,-22,8, 
  /* [4][0][][] */ 13,-53,15,105,-20,8,-30,5,-77,-37,-62,20,12,34,-30,51,-26,-57,-42,-38,-13,-27,-13,31,-35,-9,3,44,61,12,-3,54,1,28,80,21,44,127,52,92, 44,26,83,-14,-16,-16,24,-67,-43,-83,-51,0,-55,-4,-75,-61,-64,-30,-3,-57,-24,12,25,36,-34,18,-3,-33,-2,58,-38,69,-21,-6,94,79,31,82,7,56, 18,-79,-30,11,-25,-32,-5,-35,-89,-127,-61,18,-10,8,-100,-40,-100,-91,-32,-26,-3,-25,-23,-42,-35,-96,-78,-36,-31,52,50,-41,82,57,-8,81,97,105,48,-6, 
  /* [5][0][][] */ -43,5,-25,29,29,6,-66,-5,-25,48,-51,71,5,48,-38,-1,-93,13,-13,71,-47,-27,76,-110,-26,-100,11,33,-72,90,-103,77,11,-30,60,11,-25,-64,65,-46, -108,-127,23,34,7,-52,-101,-86,-90,-81,-98,-102,-37,35,-68,-34,-35,-46,65,68,45,-65,22,43,-98,1,-87,49,8,13,-66,-34,-87,27,-77,-39,10,68,-49,-95, 45,-103,64,-30,-3,-9,-45,-63,-3,65,34,11,-43,40,-82,9,46,-74,-16,-111,36,60,-84,9,-60,-98,49,37,-6,-59,-15,51,-55,-126,-93,-101,-35,-99,9,62, 
  /* [6][0][][] */ 28,69,-27,8,-46,-60,-75,-71,-113,-89,-79,-5,-75,-68,-18,3,-31,82,8,25,-38,37,-6,48,-50,-33,125,62,73,-5,34,-87,48,-108,-99,18,-120,37,-29,-42, -60,-107,44,8,-78,65,28,22,11,13,-68,64,-102,22,57,-69,9,-42,91,98,-5,-81,-30,-55,-127,75,-28,34,-58,-67,46,39,-114,34,-93,45,81,48,-92,-49, 1,-48,-59,-3,-70,-93,-41,-45,81,59,-110,-98,-20,-95,-80,-58,66,-61,35,7,-2,-96,37,-36,-27,-32,-111,-38,-65,19,-82,-37,-64,47,-23,113,-25,-95,-103,18, 
  /* [7][0][][] */ 17,-2,101,93,118,55,-49,11,-72,-80,31,-98,-30,-119,-93,-34,-42,19,-45,-14,-6,38,-38,2,41,-35,-25,42,63,63,-7,-22,43,63,3,-32,47,20,66,10, -12,44,42,48,14,-16,14,4,-50,-45,24,-95,-40,-78,-127,-93,-94,-78,-25,-62,-6,24,49,49,6,-38,-44,32,38,-11,-38,7,48,38,59,28,44,66,34,47, -4,-23,37,40,24,2,-12,-35,-80,-47,-48,-47,-124,-56,-65,-25,-38,-16,-2,-29,-3,39,40,61,-51,28,-8,32,-13,39,33,54,-49,-21,-58,6,-51,-18,59,40, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 8,1,3,40 } };
const TfArray<8, float> quant11_scale = { 8, { 0.0040136394090950489, 0.0049421600997447968, 0.0038502425886690617, 0.003201585728675127, 0.0034251634497195482, 0.002093074144795537, 0.0020414288155734539, 0.0033116345293819904, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,99,40 } };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,1,99,8 } };
const TfArray<1, float> quant13_scale = { 1, { 0.029394416138529778, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,99,1,8 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,50,1,8 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,50,8 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,50,16 } };
const TfArray<1, float> quant17_scale = { 1, { 0.027707912027835846, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,50,1,16 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,25,1,16 } };
const TfArray<2, int> tensor_dimension20 = { 2, { 1,400 } };
const TfArray<2, int> tensor_dimension21 = { 2, { 1,3 } };
const TfArray<1, float> quant21_scale = { 1, { 0.10970677435398102, } };
const TfArray<1, int> quant21_zero = { 1, { 13 } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&quant21_zero, 0 };
const TfArray<1, float> quant22_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant22 = { (TfLiteFloatArray*)&quant22_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 12 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 12,11,10 } };
const TfArray<1, int> outputs1 = { 1, { 13 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 13,2 } };
const TfArray<1, int> outputs2 = { 1, { 14 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 14 } };
const TfArray<1, int> outputs3 = { 1, { 15 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 15,3 } };
const TfArray<1, int> outputs4 = { 1, { 16 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 16,9,8 } };
const TfArray<1, int> outputs5 = { 1, { 17 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 17,4 } };
const TfArray<1, int> outputs6 = { 1, { 18 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 18 } };
const TfArray<1, int> outputs7 = { 1, { 19 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 19,5 } };
const TfArray<1, int> outputs8 = { 1, { 20 } };
const TfLiteFullyConnectedParams opdata9 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs9 = { 3, { 20,7,6 } };
const TfArray<1, int> outputs9 = { 1, { 21 } };
const TfLiteSoftmaxParams opdata10 = { 1 };
const TfArray<1, int> inputs10 = { 1, { 21 } };
const TfArray<1, int> outputs10 = { 1, { 22 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3968), (TfLiteIntArray*)&g0::tensor_dimension0, 3960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 1200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 3960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3968), (TfLiteIntArray*)&g0::tensor_dimension13, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension14, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension15, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension17, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension19, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension21, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension21, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 23, };
const size_t tflNodes_subgraph_index[] = {0, 11, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  22, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_878238_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 23;
  for (size_t i = 0; i < 23; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_878238_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_878238_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_878238_3_invoke() {
  for (size_t i = 0; i < 11; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_878238_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
